Experiment 2 (PA2) - Numerical Python [NUMPY]

In [4]:
#to grant access to the NumPy library
import numpy as np

01 - Normalization Problem 

In [12]:
#creates a random 5 x 5 ndarray
X = np.random.random ((5,5))

In [64]:
#normalize the ndaaray using the formula
mean = X.mean(axis=0) #calculates the mean along the columns  
std = X.std(axis=0) #calculates the standard deviation along the columns
X_normalized = (X - mean) / std #formula to calculate

#saving the noramlized ndarray data as 'X_normalized.npy'
np.save('X_normalized.npy', X_normalized)

print("The normalized NumPy array has been saved as ‘X_normalized.npy’.")

The normalized NumPy array has been saved as ‘X_normalized.npy’.


In [58]:
#to display the normalized NumPY (ndarray) run this cell
data = np.load('X_normalized.npy')
data

array([[-0.96519136,  1.09142346, -1.60819148,  0.68074115, -1.72774606],
       [ 0.78359563,  1.0033999 ,  1.20340592,  0.07694417,  0.99752835],
       [ 0.75610984, -0.64731721, -0.06824149,  1.31097348, -0.12440066],
       [-1.45294316, -1.54085982,  0.88805023, -1.61413325, -0.13800883],
       [ 0.87842905,  0.09335368, -0.41502318, -0.45452554,  0.99262721]])

02 - Divisible by 3 Problem

In [129]:
#generates a 10x10 ndarray with squares of the first 100 positive integers
squares = np.arange(1, 101)**2
squares_reshape = squares.reshape(10, 10)

#display the 10x10 array
print("ndarray of first 100 positive int squares has been stored to the system")
print(squares_reshape)

#find for the elements in the ndarray that are divisible by 3
div_by_3 = squares_reshape[squares_reshape % 3 == 0]

#store the elements that are divisible by 3 to a file named 'div_by_3.npy'
np.save('div_by_3.npy', div_by_3)

ndarray of first 100 positive int squares has been stored to the system
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [139]:
#load and display the stored results
data = np.load('div_by_3.npy')
print("elements divisible by 3:")
print(data)

elements divisible by 3:
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
